# Generated by Django 5.2.17 on 2026-09-03 11:55

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='sters la')),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='titlu')),
                ('content', models.TextField(blank=True, verbose_name='conținut')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, verbose_name='fixată')),
                ('source', models.CharField(choices=[('manual', 'Introdus manual'), ('voice', 'Comanda vocala'), ('scan', 'Document scanat'), ('email', 'Email'), ('calendar', 'Google Calendar')], db_index=True, default='manual', max_length=16, verbose_name='sursă')),
                ('match_text', models.TextField(blank=True, editable=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='documents.scanneddocument', verbose_name='document sursă')),
            ],
            options={
                'verbose_name': 'Notiță',
                'verbose_name_plural': 'Notițe',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='sters la')),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('is_done', models.BooleanField(default=False, verbose_name='bifat')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordine')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notes.note')),
            ],
            options={
                'verbose_name': 'Element de listă',
                'verbose_name_plural': 'Elemente de listă',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='sters la')),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=60, verbose_name='nume')),
                ('slug', models.SlugField(max_length=60, verbose_name='identificator')),
                ('color', models.CharField(choices=[('violet', 'Violet'), ('blue', 'Albastru'), ('mint', 'Verde mentă'), ('orange', 'Portocaliu')], default='violet', max_length=10, verbose_name='culoare')),
                ('icon', models.CharField(default='note', max_length=40, verbose_name='icon')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordine')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorii',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.notecategory', verbose_name='categorie'),
        ),
        migrations.AddConstraint(
            model_name='notecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('owner'), condition=models.Q(('deleted_at__isnull', True)), name='categorie_unica_pe_utilizator'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', '-updated_at'], name='note_owner_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'is_pinned'], name='note_owner_pinned_idx'),
        ),
    ]
