# Generated by Django 5.2.17 on 2026-09-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('calendar', 'Google Calendar')], max_length=16, verbose_name='serviciu')),
                ('external_account_id', models.CharField(blank=True, max_length=200, verbose_name='cont extern')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='adresă')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='permisiuni')),
                ('status', models.CharField(choices=[('disconnected', 'Neconectat'), ('connected', 'Conectat'), ('expired', 'Autorizare expirată'), ('error', 'Eroare'), ('mock', 'Demonstrativ')], default='disconnected', max_length=16, verbose_name='stare')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expiră la')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='ultima sincronizare')),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('_access_token', models.TextField(blank=True, db_column='access_token', verbose_name='token acces')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', verbose_name='token reîmprospătare')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
            ],
            options={
                'verbose_name': 'Cont conectat',
                'verbose_name_plural': 'Conturi conectate',
            },
        ),
        migrations.CreateModel(
            name='EmailReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='sters la')),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('external_message_id', models.CharField(db_index=True, max_length=200, verbose_name='id mesaj')),
                ('thread_id', models.CharField(blank=True, max_length=200)),
                ('sender', models.CharField(max_length=200, verbose_name='expeditor')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='subiect')),
                ('snippet', models.CharField(blank=True, max_length=400, verbose_name='fragment')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='primit la')),
                ('follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='de urmărit la')),
                ('status', models.CharField(choices=[('new', 'Nou'), ('follow_up', 'De urmărit'), ('done', 'Rezolvat'), ('ignored', 'Ignorat')], db_index=True, default='new', max_length=12, verbose_name='stare')),
                ('match_text', models.TextField(blank=True, editable=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='integrations.connectedaccount')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
            ],
            options={
                'verbose_name': 'Referință email',
                'verbose_name_plural': 'Referințe email',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='connectedaccount',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('provider'), name='un_cont_per_serviciu'),
        ),
        migrations.AddConstraint(
            model_name='emailreference',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('external_message_id'), name='email_unic_pe_utilizator'),
        ),
    ]
