# Generated by Django 5.2.17 on 2026-09-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreference',
            name='follow_up_note',
            field=models.TextField(blank=True, verbose_name='notă'),
        ),
    ]
