# Generated by Django 5.2.17 on 2026-09-03 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('query', models.CharField(max_length=200, verbose_name='căutare')),
                ('normalized', models.CharField(db_index=True, editable=False, max_length=200)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
            ],
            options={
                'verbose_name': 'Căutare recentă',
                'verbose_name_plural': 'Căutări recente',
                'ordering': ['-last_used_at'],
                'constraints': [models.UniqueConstraint(models.F('owner'), models.F('normalized'), name='cautare_recenta_unica')],
            },
        ),
    ]
