# Generated by Django 5.2.17 on 2026-09-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('action', models.CharField(choices=[('delete', 'Ștergere'), ('restore', 'Restaurare'), ('purge', 'Purjare definitivă'), ('external_write', 'Scriere în serviciu extern'), ('connect', 'Conectare cont'), ('disconnect', 'Deconectare cont')], db_index=True, max_length=32)),
                ('object_label', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intrare de audit',
                'verbose_name_plural': 'Intrări de audit',
                'ordering': ['-created_at'],
            },
        ),
    ]
