# Generated by Django 5.2.17 on 2026-09-03 11:55

import apps.core.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='sters la')),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('original_image', models.ImageField(upload_to=apps.core.files.upload_to_scans, verbose_name='fotografie')),
                ('processed_image', models.ImageField(blank=True, upload_to=apps.core.files.upload_to_processed, verbose_name='imagine procesată')),
                ('image_sha256', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titlu')),
                ('document_type', models.CharField(choices=[('invoice', 'Factură'), ('invitation', 'Invitație'), ('letter', 'Scrisoare'), ('receipt', 'Bon / chitanță'), ('medical', 'Document medical'), ('other', 'Alt document')], default='other', max_length=20, verbose_name='tip')),
                ('extracted_text', models.TextField(blank=True, verbose_name='text recunoscut')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='date extrase')),
                ('ocr_confidence', models.FloatField(default=0.0, verbose_name='încredere OCR')),
                ('ocr_provider', models.CharField(blank=True, editable=False, max_length=60)),
                ('processing_status', models.CharField(choices=[('pending', 'În așteptare'), ('processing', 'Se procesează'), ('ready', 'Gata de verificat'), ('confirmed', 'Confirmat'), ('failed', 'Eșuat')], db_index=True, default='pending', max_length=12, verbose_name='stare')),
                ('processing_error', models.CharField(blank=True, max_length=300)),
                ('confirmed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('match_text', models.TextField(blank=True, editable=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
            ],
            options={
                'verbose_name': 'Document scanat',
                'verbose_name_plural': 'Documente scanate',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='doc_owner_created_idx')],
            },
        ),
    ]
