# Generated by Django 5.2.17 on 2026-09-03 11:55

import apps.core.files
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='sters la')),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('audio', models.FileField(blank=True, upload_to=apps.core.files.upload_to_voice, verbose_name='înregistrare')),
                ('content_type', models.CharField(blank=True, max_length=60)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField(blank=True, verbose_name='transcriere')),
                ('transcript_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('transcribing', 'Se transcrie'), ('parsing', 'Se interpretează'), ('ready', 'Gata'), ('failed', 'Eșuat')], default='pending', max_length=14)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('mode', models.CharField(default='create', max_length=10)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
            ],
            options={
                'verbose_name': 'Captură vocală',
                'verbose_name_plural': 'Capturi vocale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('intent', models.CharField(db_index=True, max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('draft', 'Schiță'), ('clarify', 'Necesită clarificare'), ('confirmed', 'Confirmată'), ('discarded', 'Abandonată')], default='draft', max_length=12)),
                ('clarification_question', models.CharField(blank=True, max_length=300)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('target_kind', models.CharField(blank=True, max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True)),
                ('result_kind', models.CharField(blank=True, max_length=20)),
                ('result_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
                ('capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='assistant.voicecapture')),
            ],
            options={
                'verbose_name': 'Schiță',
                'verbose_name_plural': 'Schițe',
                'ordering': ['-created_at'],
            },
        ),
    ]
