# Generated by Django 5.2.17 on 2026-09-03 11:55

import apps.core.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('date', models.DateField(db_index=True, verbose_name='ziua')),
                ('generated_text', models.TextField(blank=True, verbose_name='text')),
                ('polished_text', models.TextField(blank=True, verbose_name='text reformulat')),
                ('polish_rejected_reason', models.CharField(blank=True, max_length=200)),
                ('audio_file', models.FileField(blank=True, upload_to=apps.core.files.upload_to_brief_audio, verbose_name='audio')),
                ('audio_duration_ms', models.PositiveIntegerField(default=0)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Se generează'), ('ready', 'Gata'), ('failed', 'Eșuat')], default='pending', max_length=10)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
            ],
            options={
                'verbose_name': 'Rezumat zilnic',
                'verbose_name_plural': 'Rezumate zilnice',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BriefQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True)),
                ('answered_from', models.CharField(default='deterministic', max_length=20)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='daily_brief.dailybrief')),
            ],
            options={
                'verbose_name': 'Întrebare despre zi',
                'verbose_name_plural': 'Întrebări despre zi',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailybrief',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('date'), name='un_rezumat_pe_zi'),
        ),
    ]
