# Generated by Django 5.2.17 on 2026-09-03 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('integrations', '0001_initial'),
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='sters la')),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='titlu')),
                ('description', models.TextField(blank=True, verbose_name='descriere')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='locație')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='începe la')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='se termină la')),
                ('all_day', models.BooleanField(default=False, verbose_name='toată ziua')),
                ('color', models.CharField(choices=[('violet', 'Violet'), ('blue', 'Albastru'), ('mint', 'Verde mentă'), ('orange', 'Portocaliu')], default='violet', max_length=10, verbose_name='culoare')),
                ('icon', models.CharField(default='calendar', max_length=40, verbose_name='icon')),
                ('source', models.CharField(choices=[('manual', 'Introdus manual'), ('voice', 'Comanda vocala'), ('scan', 'Document scanat'), ('email', 'Email'), ('calendar', 'Google Calendar')], db_index=True, default='manual', max_length=16, verbose_name='sursă')),
                ('external_calendar_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='id în calendarul extern')),
                ('external_synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('match_text', models.TextField(blank=True, editable=False)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='documents.scanneddocument')),
            ],
            options={
                'verbose_name': 'Programare',
                'verbose_name_plural': 'Programări',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizat la')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='sters la')),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='titlu')),
                ('description', models.TextField(blank=True, verbose_name='descriere')),
                ('remind_at', models.DateTimeField(db_index=True, verbose_name='sună la')),
                ('status', models.CharField(choices=[('scheduled', 'Programată'), ('sent', 'Trimisă'), ('snoozed', 'Amânată'), ('done', 'Rezolvată'), ('cancelled', 'Anulată')], db_index=True, default='scheduled', max_length=12, verbose_name='stare')),
                ('offset_minutes', models.PositiveIntegerField(default=0, verbose_name='decalaj față de eveniment')),
                ('source', models.CharField(choices=[('manual', 'Introdus manual'), ('voice', 'Comanda vocala'), ('scan', 'Document scanat'), ('email', 'Email'), ('calendar', 'Google Calendar')], default='manual', max_length=16, verbose_name='sursă')),
                ('notification_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('match_text', models.TextField(blank=True, editable=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='scheduling.appointment', verbose_name='programare')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='documents.scanneddocument')),
                ('email_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='integrations.emailreference')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='notes.note')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='proprietar')),
            ],
            options={
                'verbose_name': 'Alarmă',
                'verbose_name_plural': 'Alarme',
                'ordering': ['remind_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['owner', 'starts_at'], name='appt_owner_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(models.F('owner'), models.F('external_calendar_id'), condition=models.Q(('external_calendar_id', ''), _negated=True), name='programare_externa_unica'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='programare_interval_valid'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['owner', 'remind_at'], name='reminder_owner_when_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status', 'remind_at'], name='reminder_status_when_idx'),
        ),
    ]
